title: Facilitator & Consultant
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7857143
  brandStrength: 0.282997066853568
  lightness: 0.849624
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.2681704
typography_spectrum: 0.6434837
layout_spectrum: 1
name: valentinheyde
